/* WARNING: Automatically generated code.
 * This code has been generated by the DH compiler.
 */
#ifdef HAVE_CONFIG_H
#include "lushconf.h"
#endif

/*
 * USER DEFINED HEADERS
 */
#include "../roombalib.h"
/*
 * LUSH HEADERS
 */
#include "header.h"
#include "dh.h"
#include "idxmac.h"
#include "idxops.h"
#include "check_func.h"

/*
 * DECLARATIONS
 */
extern_c struct VClass_object Vt_object;
struct CClass_object;
struct CClass_roomba
{
  struct VClass_roomba *Vtbl;
  struct idx *sensors;
  gptr roombaptr;
};
struct VClass_roomba
{
  void *Cdoc;
  void (*Cdestroy) (gptr);
  char (*M_roomba) (struct CClass_roomba *, struct srg *, struct idx *,
		    struct srg *);
  char (*M__destructor) (struct CClass_roomba *);
  char (*M_drive) (struct CClass_roomba *, real, real);
  char (*M_drive_direct) (struct CClass_roomba *, real, real);
  char (*M_forward_at) (struct CClass_roomba *, real);
  char (*M_backward_at) (struct CClass_roomba *, real);
  char (*M_spinleft_at) (struct CClass_roomba *, real);
  char (*M_spinright_at) (struct CClass_roomba *, real);
  char (*M_stop) (struct CClass_roomba *);
  char (*M_digital_out) (struct CClass_roomba *, unsigned char);
  int (*M_read_sensors) (struct CClass_roomba *, int);
};
extern_c struct VClass_roomba Vt_roomba;
extern_c char C_idx_u1resize (struct idx *, int);
extern_c char C_roomba_C_roomba (struct CClass_roomba *, struct srg *,
				 struct idx *, struct srg *);
extern_c char C__destructor_C_roomba (struct CClass_roomba *);
extern_c char C_drive_C_roomba (struct CClass_roomba *, real, real);
extern_c char C_drive_direct_C_roomba (struct CClass_roomba *, real, real);
extern_c char C_forward_at_C_roomba (struct CClass_roomba *, real);
extern_c char C_backward_at_C_roomba (struct CClass_roomba *, real);
extern_c char C_spinleft_at_C_roomba (struct CClass_roomba *, real);
extern_c char C_spinright_at_C_roomba (struct CClass_roomba *, real);
extern_c char C_stop_C_roomba (struct CClass_roomba *);
extern_c char C_digital_out_C_roomba (struct CClass_roomba *, unsigned char);
extern_c int C_read_sensors_C_roomba (struct CClass_roomba *, int);

/* ---------------------------------------- */

/*
 * FUNCTION bytes2short
 */
extern_c real
C_bytes2short (struct idx *L1_m, int L1_n)
{
  TRACE_PUSH ("C_bytes2short");
  {
    real L_Tmp0;
    {
      real L2_1_r;
      L2_1_r = 0;
      {
	uint8_t *p = IDX_PTR ((L1_m), uint8_t);
	(L2_1_r) = (double) ((p[(L1_n)] << 8) + p[(L1_n) + 1]);
      }
      L_Tmp0 = L2_1_r;
    }
    TRACE_POP ("C_bytes2short");
    return L_Tmp0;
  }
}

/*
 * METHOD FUNCTION roomba (class roomba)
 */
extern_c char
C_roomba_C_roomba (struct CClass_roomba *L1_this, struct srg *L1_portname,
		   struct idx *L1_0_matrix, struct srg *L1_0_srg)
{
  TRACE_PUSH ("C_roomba_C_roomba");
  {
    (L1_this->roombaptr) = (void *) (roomba_init (SADD ((L1_portname))));
    if ((L1_this->roombaptr) == NULL)
      {
	run_time_error ("could not open roomba port");
      }
    (L1_0_matrix)->srg = L1_0_srg;
    Midx_init_dim1 (L1_0_matrix, 52);
    RTERR_DIM (L1_0_matrix->dim[0] <= 0);
    Midx_maclear (L1_0_matrix, unsigned char);
    L1_this->sensors = L1_0_matrix;
    TRACE_POP ("C_roomba_C_roomba");
    return 0;
  }
}

/*
 * METHOD FUNCTION -destructor (class roomba)
 */
extern_c char
C__destructor_C_roomba (struct CClass_roomba *L1_this)
{
  TRACE_PUSH ("C__destructor_C_roomba");
  {
    if (L1_this->roombaptr)
      {
	roomba_free ((Roomba *) (L1_this->roombaptr));
      }
    TRACE_POP ("C__destructor_C_roomba");
    return 0;
  }
}

/*
 * METHOD FUNCTION drive (class roomba)
 */
extern_c char
C_drive_C_roomba (struct CClass_roomba *L1_this, real L1_velocity,
		  real L1_radius)
{
  TRACE_PUSH ("C_drive_C_roomba");
  {
    roomba_drive ((Roomba *) ((L1_this->roombaptr)), (int) ((L1_velocity)),
		  (int) ((L1_radius)));
    TRACE_POP ("C_drive_C_roomba");
    return 0;
  }
}

/*
 * METHOD FUNCTION drive-direct (class roomba)
 */
extern_c char
C_drive_direct_C_roomba (struct CClass_roomba *L1_this, real L1_vleft,
			 real L1_vright)
{
  TRACE_PUSH ("C_drive_direct_C_roomba");
  {
    roomba_drive_direct ((Roomba *) ((L1_this->roombaptr)),
			 (int) ((L1_vleft)), (int) ((L1_vright)));
    TRACE_POP ("C_drive_direct_C_roomba");
    return 0;
  }
}

/*
 * METHOD FUNCTION forward-at (class roomba)
 */
extern_c char
C_forward_at_C_roomba (struct CClass_roomba *L1_this, real L1_velocity)
{
  TRACE_PUSH ("C_forward_at_C_roomba");
  {
    roomba_forward_at ((Roomba *) ((L1_this->roombaptr)),
		       (int) (L1_velocity));
    TRACE_POP ("C_forward_at_C_roomba");
    return 0;
  }
}

/*
 * METHOD FUNCTION backward-at (class roomba)
 */
extern_c char
C_backward_at_C_roomba (struct CClass_roomba *L1_this, real L1_velocity)
{
  TRACE_PUSH ("C_backward_at_C_roomba");
  {
    roomba_backward_at ((Roomba *) ((L1_this->roombaptr)),
			(int) (L1_velocity));
    TRACE_POP ("C_backward_at_C_roomba");
    return 0;
  }
}

/*
 * METHOD FUNCTION spinleft-at (class roomba)
 */
extern_c char
C_spinleft_at_C_roomba (struct CClass_roomba *L1_this, real L1_velocity)
{
  TRACE_PUSH ("C_spinleft_at_C_roomba");
  {
    roomba_spinleft_at ((Roomba *) ((L1_this->roombaptr)),
			(int) (L1_velocity));
    TRACE_POP ("C_spinleft_at_C_roomba");
    return 0;
  }
}

/*
 * METHOD FUNCTION spinright-at (class roomba)
 */
extern_c char
C_spinright_at_C_roomba (struct CClass_roomba *L1_this, real L1_velocity)
{
  TRACE_PUSH ("C_spinright_at_C_roomba");
  {
    roomba_spinright_at ((Roomba *) ((L1_this->roombaptr)),
			 (int) (L1_velocity));
    TRACE_POP ("C_spinright_at_C_roomba");
    return 0;
  }
}

/*
 * METHOD FUNCTION stop (class roomba)
 */
extern_c char
C_stop_C_roomba (struct CClass_roomba *L1_this)
{
  TRACE_PUSH ("C_stop_C_roomba");
  {
    roomba_stop ((Roomba *) ((L1_this->roombaptr)));
    TRACE_POP ("C_stop_C_roomba");
    return 0;
  }
}

/*
 * METHOD FUNCTION digital-out (class roomba)
 */
extern_c char
C_digital_out_C_roomba (struct CClass_roomba *L1_this, unsigned char L1_bits)
{
  TRACE_PUSH ("C_digital_out_C_roomba");
  {
    roomba_digital_out ((Roomba *) ((L1_this->roombaptr)), (L1_bits));
    TRACE_POP ("C_digital_out_C_roomba");
    return 0;
  }
}

/*
 * METHOD FUNCTION read-sensors (class roomba)
 */
extern_c int
C_read_sensors_C_roomba (struct CClass_roomba *L1_this, int L1_group)
{
  TRACE_PUSH ("C_read_sensors_C_roomba");
  {
    int L_Tmp0;
    {
      int L2_1_err;
      L2_1_err = 0;
      C_idx_u1resize (L1_this->sensors, 52);
      (L2_1_err) =
	roomba_read_sensors ((Roomba *) ((L1_this->roombaptr)), (L1_group));
      memcpy (IDX_PTR ((L1_this->sensors), uint8_t),
	      ((Roomba *) (L1_this->roombaptr))->sensor_bytes, 26);
      L_Tmp0 = L2_1_err;
    }
    TRACE_POP ("C_read_sensors_C_roomba");
    return L_Tmp0;
  }
}

/*
 * CLASS roomba DESTROY
 */
static void
Cdestroy_C_roomba (gptr g)
{
  C__destructor_C_roomba ((struct CClass_roomba *) g);
}

/*
 * CLASS roomba VTABLE
 */
struct VClass_roomba Vt_roomba = {
  (void *) &Vt_object,
  &Cdestroy_C_roomba,
  &C_roomba_C_roomba,
  &C__destructor_C_roomba,
  &C_drive_C_roomba,
  &C_drive_direct_C_roomba,
  &C_forward_at_C_roomba,
  &C_backward_at_C_roomba,
  &C_spinleft_at_C_roomba,
  &C_spinright_at_C_roomba,
  &C_stop_C_roomba,
  &C_digital_out_C_roomba,
  &C_read_sensors_C_roomba,
};

/* ---------------------------------------- */

#ifndef NOLISP

/* Declarations */
extern_c dhclassdoc_t Kc_object;
extern_c dhclassdoc_t Kc_roomba_Re1c75e46;
extern_c dhdoc_t K_idx_u1resize_R61894f3f;

/*
 * STUB bytes2short
 */
DH (X_bytes2short)
{
  dharg ret;
  ret.dh_real = C_bytes2short (a[1].dh_idx_ptr, a[2].dh_int);
  return ret;
}

/*
 * DHDOC bytes2short
 */
DHDOC (K_bytes2short_Re3016b12, X_bytes2short, "C_bytes2short", 0, 0) =
{
DH_FUNC (2),
    DH_IDX (DHT_READ, 1),
    DH_SRG (DHT_READ),
    DH_UBYTE, DH_INT, DH_RETURN, DH_REAL, DH_END_FUNC, DH_NIL};

/*
 * METHOD STUB roomba (class roomba)
 */
DH (X_roomba_C_roomba)
{
  dharg ret;
  ret.dh_char =
    C_roomba_C_roomba ((struct CClass_roomba *) a[1].dh_obj_ptr,
		       a[2].dh_srg_ptr, a[3].dh_idx_ptr, a[4].dh_srg_ptr);
  return ret;
}

/*
 * METHOD DHDOC roomba (class roomba)
 */
DHDOC (K_roomba_C_roomba_Re30d338f, X_roomba_C_roomba, "C_roomba_C_roomba", 0,
       0) =
{
DH_FUNC (2),
    DH_OBJ (Kc_roomba_Re1c75e46),
    DH_STR,
    DH_TEMPS (2),
    DH_IDX (DHT_WRITE, 1), DH_UBYTE,
    DH_SRG (DHT_WRITE), DH_UBYTE,
    DH_END_TEMPS, DH_RETURN, DH_NIL, DH_END_FUNC, DH_NIL};

/*
 * METHOD STUB -destructor (class roomba)
 */
DH (X__destructor_C_roomba)
{
  dharg ret;
  ret.dh_char =
    C__destructor_C_roomba ((struct CClass_roomba *) a[1].dh_obj_ptr);
  return ret;
}

/*
 * METHOD DHDOC -destructor (class roomba)
 */
DHDOC (K__destructor_C_roomba_Re34bd8dc, X__destructor_C_roomba,
       "C__destructor_C_roomba", 0, 0) =
{
DH_FUNC (1),
    DH_OBJ (Kc_roomba_Re1c75e46), DH_RETURN, DH_NIL, DH_END_FUNC, DH_NIL};

/*
 * METHOD STUB drive (class roomba)
 */
DH (X_drive_C_roomba)
{
  dharg ret;
  ret.dh_char =
    C_drive_C_roomba ((struct CClass_roomba *) a[1].dh_obj_ptr, a[2].dh_real,
		      a[3].dh_real);
  return ret;
}

/*
 * METHOD DHDOC drive (class roomba)
 */
DHDOC (K_drive_C_roomba_Ra4a50ccb, X_drive_C_roomba, "C_drive_C_roomba", 0,
       0) =
{
DH_FUNC (3),
    DH_OBJ (Kc_roomba_Re1c75e46),
    DH_REAL, DH_REAL, DH_RETURN, DH_NIL, DH_END_FUNC, DH_NIL};

/*
 * METHOD STUB drive-direct (class roomba)
 */
DH (X_drive_direct_C_roomba)
{
  dharg ret;
  ret.dh_char =
    C_drive_direct_C_roomba ((struct CClass_roomba *) a[1].dh_obj_ptr,
			     a[2].dh_real, a[3].dh_real);
  return ret;
}

/*
 * METHOD DHDOC drive-direct (class roomba)
 */
DHDOC (K_drive_direct_C_roomba_Ra4a50ccb, X_drive_direct_C_roomba,
       "C_drive_direct_C_roomba", 0, 0) =
{
DH_FUNC (3),
    DH_OBJ (Kc_roomba_Re1c75e46),
    DH_REAL, DH_REAL, DH_RETURN, DH_NIL, DH_END_FUNC, DH_NIL};

/*
 * METHOD STUB forward-at (class roomba)
 */
DH (X_forward_at_C_roomba)
{
  dharg ret;
  ret.dh_char =
    C_forward_at_C_roomba ((struct CClass_roomba *) a[1].dh_obj_ptr,
			   a[2].dh_real);
  return ret;
}

/*
 * METHOD DHDOC forward-at (class roomba)
 */
DHDOC (K_forward_at_C_roomba_R21ee6b2e, X_forward_at_C_roomba,
       "C_forward_at_C_roomba", 0, 0) =
{
DH_FUNC (2),
    DH_OBJ (Kc_roomba_Re1c75e46),
    DH_REAL, DH_RETURN, DH_NIL, DH_END_FUNC, DH_NIL};

/*
 * METHOD STUB backward-at (class roomba)
 */
DH (X_backward_at_C_roomba)
{
  dharg ret;
  ret.dh_char =
    C_backward_at_C_roomba ((struct CClass_roomba *) a[1].dh_obj_ptr,
			    a[2].dh_real);
  return ret;
}

/*
 * METHOD DHDOC backward-at (class roomba)
 */
DHDOC (K_backward_at_C_roomba_R21ee6b2e, X_backward_at_C_roomba,
       "C_backward_at_C_roomba", 0, 0) =
{
DH_FUNC (2),
    DH_OBJ (Kc_roomba_Re1c75e46),
    DH_REAL, DH_RETURN, DH_NIL, DH_END_FUNC, DH_NIL};

/*
 * METHOD STUB spinleft-at (class roomba)
 */
DH (X_spinleft_at_C_roomba)
{
  dharg ret;
  ret.dh_char =
    C_spinleft_at_C_roomba ((struct CClass_roomba *) a[1].dh_obj_ptr,
			    a[2].dh_real);
  return ret;
}

/*
 * METHOD DHDOC spinleft-at (class roomba)
 */
DHDOC (K_spinleft_at_C_roomba_R21ee6b2e, X_spinleft_at_C_roomba,
       "C_spinleft_at_C_roomba", 0, 0) =
{
DH_FUNC (2),
    DH_OBJ (Kc_roomba_Re1c75e46),
    DH_REAL, DH_RETURN, DH_NIL, DH_END_FUNC, DH_NIL};

/*
 * METHOD STUB spinright-at (class roomba)
 */
DH (X_spinright_at_C_roomba)
{
  dharg ret;
  ret.dh_char =
    C_spinright_at_C_roomba ((struct CClass_roomba *) a[1].dh_obj_ptr,
			     a[2].dh_real);
  return ret;
}

/*
 * METHOD DHDOC spinright-at (class roomba)
 */
DHDOC (K_spinright_at_C_roomba_R21ee6b2e, X_spinright_at_C_roomba,
       "C_spinright_at_C_roomba", 0, 0) =
{
DH_FUNC (2),
    DH_OBJ (Kc_roomba_Re1c75e46),
    DH_REAL, DH_RETURN, DH_NIL, DH_END_FUNC, DH_NIL};

/*
 * METHOD STUB stop (class roomba)
 */
DH (X_stop_C_roomba)
{
  dharg ret;
  ret.dh_char = C_stop_C_roomba ((struct CClass_roomba *) a[1].dh_obj_ptr);
  return ret;
}

/*
 * METHOD DHDOC stop (class roomba)
 */
DHDOC (K_stop_C_roomba_Re34bd8dc, X_stop_C_roomba, "C_stop_C_roomba", 0, 0) =
{
DH_FUNC (1),
    DH_OBJ (Kc_roomba_Re1c75e46), DH_RETURN, DH_NIL, DH_END_FUNC, DH_NIL};

/*
 * METHOD STUB digital-out (class roomba)
 */
DH (X_digital_out_C_roomba)
{
  dharg ret;
  ret.dh_char =
    C_digital_out_C_roomba ((struct CClass_roomba *) a[1].dh_obj_ptr,
			    a[2].dh_uchar);
  return ret;
}

/*
 * METHOD DHDOC digital-out (class roomba)
 */
DHDOC (K_digital_out_C_roomba_R44ea5d56, X_digital_out_C_roomba,
       "C_digital_out_C_roomba", 0, 0) =
{
DH_FUNC (2),
    DH_OBJ (Kc_roomba_Re1c75e46),
    DH_UBYTE, DH_RETURN, DH_NIL, DH_END_FUNC, DH_NIL};

/*
 * METHOD STUB read-sensors (class roomba)
 */
DH (X_read_sensors_C_roomba)
{
  dharg ret;
  ret.dh_int =
    C_read_sensors_C_roomba ((struct CClass_roomba *) a[1].dh_obj_ptr,
			     a[2].dh_int);
  return ret;
}

/*
 * METHOD DHDOC read-sensors (class roomba)
 */
DHDOC (K_read_sensors_C_roomba_Rca9e5bae, X_read_sensors_C_roomba,
       "C_read_sensors_C_roomba", 0, 0) =
{
DH_FUNC (2),
    DH_OBJ (Kc_roomba_Re1c75e46),
    DH_INT,
    DH_RETURN,
    DH_INT, DH_END_FUNC, DH_REFER (K_idx_u1resize_R61894f3f), DH_NIL};

/*
 * CLASS roomba DHCLASSDOC
 */
DHCLASSDOC (Kc_roomba_Re1c75e46, &Kc_object, roomba, "roomba", Vt_roomba,
	    11) =
{
DH_CLASS (2, Kc_roomba_Re1c75e46),
    DH_NAME ("sensors", roomba, sensors),
    DH_IDX (DHT_READ, 1),
    DH_SRG (DHT_READ),
    DH_UBYTE,
    DH_NAME ("roombaptr", roomba, roombaptr),
    DH_GPTR (0),
    DH_END_CLASS,
    DH_METHOD ("roomba", K_roomba_C_roomba_Re30d338f),
    DH_METHOD ("_destructor", K__destructor_C_roomba_Re34bd8dc),
    DH_METHOD ("drive", K_drive_C_roomba_Ra4a50ccb),
    DH_METHOD ("drive_direct", K_drive_direct_C_roomba_Ra4a50ccb),
    DH_METHOD ("forward_at", K_forward_at_C_roomba_R21ee6b2e),
    DH_METHOD ("backward_at", K_backward_at_C_roomba_R21ee6b2e),
    DH_METHOD ("spinleft_at", K_spinleft_at_C_roomba_R21ee6b2e),
    DH_METHOD ("spinright_at", K_spinright_at_C_roomba_R21ee6b2e),
    DH_METHOD ("stop", K_stop_C_roomba_Re34bd8dc),
    DH_METHOD ("digital_out", K_digital_out_C_roomba_R44ea5d56),
    DH_METHOD ("read_sensors", K_read_sensors_C_roomba_Rca9e5bae), DH_NIL};

/*
 * INIT FUNCTION
 */
extern_c void
init_roomba (void)
{
  dh_define ("bytes2short", &K_bytes2short_Re3016b12);
  dhclass_define ("roomba", &Kc_roomba_Re1c75e46);
  dhmethod_define (&Kc_roomba_Re1c75e46, "roomba",
		   &K_roomba_C_roomba_Re30d338f);
  dhmethod_define (&Kc_roomba_Re1c75e46, "-destructor",
		   &K__destructor_C_roomba_Re34bd8dc);
  dhmethod_define (&Kc_roomba_Re1c75e46, "drive",
		   &K_drive_C_roomba_Ra4a50ccb);
  dhmethod_define (&Kc_roomba_Re1c75e46, "drive-direct",
		   &K_drive_direct_C_roomba_Ra4a50ccb);
  dhmethod_define (&Kc_roomba_Re1c75e46, "forward-at",
		   &K_forward_at_C_roomba_R21ee6b2e);
  dhmethod_define (&Kc_roomba_Re1c75e46, "backward-at",
		   &K_backward_at_C_roomba_R21ee6b2e);
  dhmethod_define (&Kc_roomba_Re1c75e46, "spinleft-at",
		   &K_spinleft_at_C_roomba_R21ee6b2e);
  dhmethod_define (&Kc_roomba_Re1c75e46, "spinright-at",
		   &K_spinright_at_C_roomba_R21ee6b2e);
  dhmethod_define (&Kc_roomba_Re1c75e46, "stop", &K_stop_C_roomba_Re34bd8dc);
  dhmethod_define (&Kc_roomba_Re1c75e46, "digital-out",
		   &K_digital_out_C_roomba_R44ea5d56);
  dhmethod_define (&Kc_roomba_Re1c75e46, "read-sensors",
		   &K_read_sensors_C_roomba_Rca9e5bae);
}

int majver_roomba = 40;
int minver_roomba = 10;

#endif
